# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yk1QIkSDFEPoymYK8kaYxqOptHAuMPeF
"""

x = input()
print("Hello World ," + x)